dist:
  name: mdai-collector
  description: MyDecisive Debug Collector
  output_path: ./cmd/mdai-collector

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.144.0
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.144.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.144.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.144.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awss3exporter v0.144.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.144.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.144.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.144.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbyattrsprocessor v0.144.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor v0.144.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.144.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8seventsreceiver v0.144.0

connectors:
  - gomod: github.com/decisiveai/mdai-collectors/datavolumeconnector v0.1.3
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/routingconnector v0.144.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/countconnector v0.144.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/cgroupruntimeextension v0.144.0

replaces:
  # a list of "replaces" directives that will be part of the resulting go.mod
  - github.com/decisiveai/mdai-collectors/datavolumeconnector => ../../datavolumeconnector