apiVersion: apps/v1
kind: Deployment
metadata:
  name: observer-collector
  labels:
    app: observer-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: observer-collector
  template:
    metadata:
      labels:
        app: observer-collector
        app.kubernetes.io/component: observer-collector
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8899"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: observer-collector
          image: public.ecr.aws/decisiveai/observer-collector:0.1.5
          ports:
            - containerPort: 8888
              name: otelcol-metrics
            - containerPort: 8899
              name: obs-metrics
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
          volumeMounts:
            - name: config-volume
              mountPath: /conf/collector.yaml
              subPath: collector.yaml
          command:
            - "/mdai-observer-collector"
            - "--config=/conf/collector.yaml"
      volumes:
        - name: config-volume
          configMap:
            name: observer-collector-config