apiVersion: v1
kind: Service
metadata:
  name: observer-collector-service
  labels:
    app: observer-collector
spec:
  selector:
    app: observer-collector
  ports:
    - port: 4317
      targetPort: otlp-grpc
      protocol: TCP
      name: otlp-grpc
    - port: 4318
      targetPort: otlp-http
      protocol: TCP
      name: otlp-http
    - port: 8899
      targetPort: obs-metrics
      protocol: TCP
      name: obs-metrics
  type: ClusterIP
